project:
  type: website
  output-dir: docs/en

website:
  title: "Wedding"
  favicon: favicon.png
  navbar:
    background: transparent
    left:
      - href: index.qmd
        text: Info
      - href: itinerary_en.qmd
        text: Itinerary
    right:
      - href: ..
        text: 🇨🇿

lang: en

