project:
  type: website
  output-dir: docs

website:
  title: "Svatba"
  favicon: favicon.png
  navbar:
    background: transparent
    left:
      - file: index.qmd
        text: Úvod
      - href: harmonogram.qmd
        text: Harmonogram
      - href: obrad.qmd
        text: Obřad
      - href: ubytovani.qmd
        text: Ubytování
      - href: dary.qmd
        text: Dary

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true