project:
  type: website
  output-dir: docs

website:
  title: "Svatba"
  favicon: favicon.png
  navbar:
    background: transparent
    left:
      - file: index.qmd
        text: Úvod
      - href: harmonogram.qmd
        text: Harmonogram
      - href: dary.qmd
        text: Dary
      - href: ubytovani.qmd
        text: Ubytování

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true